// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxP6W4doe4Rd4lgsm3ucsv5w32xlu_wwg',
    appId: '1:102107248369:web:0e973fadbbfe06bc209b50',
    messagingSenderId: '102107248369',
    projectId: 'chatapp-flutter-93ef4',
    authDomain: 'chatapp-flutter-93ef4.firebaseapp.com',
    storageBucket: 'chatapp-flutter-93ef4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_YYoIFYeMp7lldxL3SQMBp1nx6b65Dr8',
    appId: '1:102107248369:android:179a37433398be06209b50',
    messagingSenderId: '102107248369',
    projectId: 'chatapp-flutter-93ef4',
    storageBucket: 'chatapp-flutter-93ef4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnCFh0nyFzatjJ1zms1qZ5IckSISlbv4A',
    appId: '1:102107248369:ios:bdc3e0d2e8f822c3209b50',
    messagingSenderId: '102107248369',
    projectId: 'chatapp-flutter-93ef4',
    storageBucket: 'chatapp-flutter-93ef4.appspot.com',
    iosBundleId: 'com.example.chatAppFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnCFh0nyFzatjJ1zms1qZ5IckSISlbv4A',
    appId: '1:102107248369:ios:bdc3e0d2e8f822c3209b50',
    messagingSenderId: '102107248369',
    projectId: 'chatapp-flutter-93ef4',
    storageBucket: 'chatapp-flutter-93ef4.appspot.com',
    iosBundleId: 'com.example.chatAppFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxP6W4doe4Rd4lgsm3ucsv5w32xlu_wwg',
    appId: '1:102107248369:web:60434fc1955ae3fc209b50',
    messagingSenderId: '102107248369',
    projectId: 'chatapp-flutter-93ef4',
    authDomain: 'chatapp-flutter-93ef4.firebaseapp.com',
    storageBucket: 'chatapp-flutter-93ef4.appspot.com',
  );
}